# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.2.4
_src_path: gh:algorandfoundation/algokit-python-template
author_email: rajankur1802@gmail.com
author_name: Ankur Raj
contract_name: hello_world
deployment_language: typescript
preset_name: starter
project_name: Algo-project-contracts

